services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - 5001:5000
    networks:
      - api_bridge
    restart: always

  frontend:
    build:
      context: ./frontend/ui
      dockerfile: Dockerfile
    volumes:
      - ./frontend/ui:/ui
      - /ui/node_modules
    ports:
      - 3007:8080
    networks:
      - api_bridge
    restart: always

networks:
  api_bridge:
    driver: bridge